export function getCountryIsoCode(country: string): string {
  if (!country) return "un";
  const normalized = country.toLowerCase().trim();
  
  const map: Record<string, string> = {
    // English names
    "united states": "us",
    "united states of america": "us",
    "usa": "us",
    "germany": "de",
    "united arab emirates": "ae",
    "uae": "ae",
    "united kingdom": "gb",
    "uk": "gb",
    "south korea": "kr",
    "north korea": "kp",
    "south africa": "za",
    "new zealand": "nz",
    "saudi arabia": "sa",
    "czech republic": "cz",
    "netherlands": "nl",
    "switzerland": "ch",
    "singapore": "sg",
    "qatar": "qa",
    "turkey": "tr",
    "turkiye": "tr",
    "malaysia": "my",
    "thailand": "th",
    "hong kong": "hk",
    "vietnam": "vn",
    "philippines": "ph",
    "egypt": "eg",
    "mexico": "mx",
    "brazil": "br",
    "china": "cn",
    "canada": "ca",
    "australia": "au",
    "india": "in",
    "netherlands/aruba": "aw",
    "japan": "jp",
    "france": "fr",
    "italy": "it",
    "spain": "es",
    "ireland": "ie",
    "finland": "fi",
    "sweden": "se",
    "norway": "no",
    "denmark": "dk",
    "belgium": "be",
    "austria": "at",
    "portugal": "pt",

    // Italian names
    "afghanistan": "af",
    "albania": "al",
    "algeria": "dz",
    "angola": "ao",
    "antigua e barbuda": "ag",
    "arabia saudita": "sa",
    "argentina": "ar",
    "armenia": "am",
    "aruba": "aw",
    "austria (paese)": "at",
    "azerbaigian": "az",
    "bahamas": "bs",
    "bahrein": "bh",
    "bangladesh": "bd",
    "barbados": "bb",
    "belgio": "be",
    "belize": "bz",
    "benin": "bj",
    "bhutan": "bt",
    "bielorussia": "by",
    "bolivia": "bo",
    "bosnia ed erzegovina": "ba",
    "botswana": "bw",
    "brasile": "br",
    "brunei": "bn",
    "bulgaria": "bg",
    "burkina faso": "bf",
    "burundi": "bi",
    "cambogia": "kh",
    "camerun": "cm",
    "capo verde": "cv",
    "cecoslovacchia": "cz",
    "ciad": "td",
    "cile": "cl",
    "cina": "cn",
    "cipro": "cy",
    "cipro del nord": "cy",
    "colombia": "co",
    "comore": "km",
    "corea del nord": "kp",
    "corea del sud": "kr",
    "costa rica": "cr",
    "costa d'avorio": "ci",
    "croazia": "hr",
    "cuba": "cu",
    "curaçao": "cw",
    "danimarca": "dk",
    "dominica": "dm",
    "ecuador": "ec",
    "egitto": "eg",
    "el salvador": "sv",
    "emirati arabi uniti": "ae",
    "eritrea": "er",
    "estonia": "ee",
    "eswatini": "sz",
    "etiopia": "et",
    "figi": "fj",
    "filippine": "ph",
    "finlandia": "fi",
    "francia": "fr",
    "fær øer": "fo",
    "gabon": "ga",
    "gambia": "gm",
    "georgia": "ge",
    "germania": "de",
    "ghana": "gh",
    "giamaica": "jm",
    "giappone": "jp",
    "gibuti": "dj",
    "giordania": "jo",
    "grecia": "gr",
    "grenada": "gd",
    "groenlandia": "gl",
    "guatemala": "gt",
    "guernsey": "gg",
    "guinea": "gn",
    "guinea equatoriale": "gq",
    "guinea-bissau": "gw",
    "guyana": "gy",
    "haiti": "ht",
    "honduras": "hn",
    "impero giapponese": "jp",
    "indonesia": "id",
    "internazionale": "un",
    "iran": "ir",
    "iraq": "iq",
    "irlanda": "ie",
    "islanda": "is",
    "isole cook": "ck",
    "isole marshall": "mh",
    "isole salomone": "sb",
    "isole vergini britanniche": "vg",
    "israele": "il",
    "italia": "it",
    "jersey": "je",
    "kazakistan": "kz",
    "kenya": "ke",
    "kirghizistan": "kg",
    "kiribati": "ki",
    "kosovo": "xk",
    "kuwait": "kw",
    "laos": "la",
    "lesotho": "ls",
    "lettonia": "lv",
    "libano": "lb",
    "liberia": "lr",
    "libia": "ly",
    "lituania": "lt",
    "lussemburgo": "lu",
    "macedonia del nord": "mk",
    "madagascar": "mg",
    "malawi": "mw",
    "maldive": "mv",
    "mali": "ml",
    "malta": "mt",
    "marocco": "ma",
    "mauritania": "mr",
    "mauritius": "mu",
    "messico": "mx",
    "moldavia": "md",
    "mongolia": "mn",
    "montenegro": "me",
    "mozambico": "mz",
    "myanmar": "mm",
    "namibia": "na",
    "nauru": "nr",
    "nepal": "np",
    "nicaragua": "ni",
    "niger": "ne",
    "nigeria": "ng",
    "niue": "nu",
    "norvegia": "no",
    "nuova zelanda": "nz",
    "oman": "om",
    "paesi bassi": "nl",
    "pakistan": "pk",
    "palau": "pw",
    "panama": "pa",
    "papua nuova guinea": "pg",
    "paraguay": "py",
    "perù": "pe",
    "polonia": "pl",
    "portogallo": "pt",
    "principato di monaco": "mc",
    "regno unito": "gb",
    "repubblica ceca": "cz",
    "repubblica centrafricana": "cf",
    "repubblica democratica popolare dello yemen": "ye",
    "repubblica democratica tedesca": "de",
    "repubblica democratica del congo": "cd",
    "repubblica dominicana": "do",
    "repubblica del congo": "cg",
    "romania": "ro",
    "ruanda": "rw",
    "russia": "ru",
    "sahara occidentale": "eh",
    "saint lucia": "lc",
    "saint vincent e grenadine": "vc",
    "samoa": "ws",
    "san marino": "sm",
    "senegal": "sn",
    "serbia": "rs",
    "seychelles": "sc",
    "sierra leone": "sl",
    "sint maarten": "sx",
    "siria": "sy",
    "slovacchia": "sk",
    "slovenia": "si",
    "somalia": "so",
    "spagna": "es",
    "sri lanka": "lk",
    "stati federati di micronesia": "fm",
    "stati uniti": "us",
    "stati uniti d'america": "us",
    "stato di palestina": "ps",
    "sudafrica": "za",
    "sudan": "sd",
    "sudan del sud": "ss",
    "suriname": "sr",
    "svezia": "se",
    "svezia/norvegia/danimarca": "se",
    "svizzera": "ch",
    "são tomé e príncipe": "st",
    "tagikistan": "tj",
    "taiwan": "tw",
    "tanzania": "tz",
    "thailandia": "th",
    "timor est": "tl",
    "togo": "tg",
    "tonga": "to",
    "trinidad e tobago": "tt",
    "tunisia": "tn",
    "turchia": "tr",
    "turkmenistan": "tm",
    "turks e caicos": "tc",
    "tuvalu": "tv",
    "ucraina": "ua",
    "uganda": "ug",
    "ungheria": "hu",
    "uruguay": "uy",
    "uzbekistan": "uz",
    "vanuatu": "vu",
    "venezuela": "ve",
    "yemen": "ye",
    "zambia": "zm",
    "zimbabwe": "zw",
    "isola di man": "im"
  };

  return map[normalized] || "un";
}
